### ISSUE TITLE
[feature] 삭제 스케줄러에 카테고리 추가

### ISSUE THREAD

**Issue by dahyen0o** [Floney-2023/Floney-Server#273]
## 📍 구현할 기능

> mysql 이벤트 스케줄러에 카테고리 삭제 추가

## 🛠 작업 내용

- [x] mysql 이벤트 스케줄러에 카테고리 삭제 추가

## 💬 기타 사항

-

**Comment by sienna011022** [comment]
<pre>
-- Alter the event named 'event_name'
delimiter |
ALTER EVENT delete_event
ON SCHEDULE EVERY 1 DAY 
DO BEGIN
	delete
	FROM category
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';
    
	delete
	FROM alarm
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';

	delete
	FROM asset
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';
    
    delete
	FROM book
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';
    
	delete
	FROM book_line
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';

	delete
	FROM book_line_category
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';

	delete
	FROM book_user
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';

	delete
	FROM budget
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';

	delete
	FROM carry_over
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';
    
    delete
	FROM category
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';

	delete
	FROM settlement
	WHERE created_at < DATE_SUB(NOW(), INTERVAL 3 MONTH);

	delete
	FROM settlement_user
	WHERE created_at < DATE_SUB(NOW(), INTERVAL 3 MONTH);

	delete
	FROM subscribe
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';

	delete
	FROM `user`
	WHERE updated_at < DATE_SUB(NOW(), INTERVAL 3 MONTH)
	AND status = 'INACTIVE';

END|
delimiter ;
</pre>

**Comment by dahyen0o** [comment]
@sienna011022 음? 맨 위에 추가하신거 지워야 할 것 같아요
제가 아래에 써놨었네요 ㅋㅋ

**Comment by sienna011022** [comment]
> @sienna011022 음? 맨 위에 추가하신거 지워야 할 것 같아요 제가 아래에 써놨었네요 ㅋㅋ

엇 그러네여
