### ISSUE TITLE
[refactor] 위임 로직 리팩토링 , 테스트 코드 작성

### ISSUE THREAD

**Issue by sienna011022** [Floney-2023/Floney-Server#279]
## 📍 구현할 기능

> 위임 로직 리팩토링 , 테스트 코드 작성

## 🛠 작업 내용

- [ ] 위임 로직 book도메인으로 이동하여 리팩토링 
- [ ] 위임 로직 테스트 코드 작성

## 💬 기타 사항

-

**Comment by dahyen0o** [comment]
기획에서 구독이 삭제되어 해당 이슈 또한 닫겠습니다.
