### ISSUE TITLE
[infra] 실 운영 서버 구성

### ISSUE THREAD

**Issue by sienna011022** [Floney-2023/Floney-Server#282]
## 📍 구현할 기능

>  실 운영 서버 구성

## 🛠 작업 내용

- [x] EC2, RDS 구축
- [x] RDS에 DB 스키마 생성
- [x] #286
- [ ] 보안 접근 관리 살펴보기
- [ ] WAF 도입 고려
- [x] EC2 스왑 메모리 추가
- [x] https 도메인 연결
- [x] EC2 시간 한국 시간으로 변경
- [x] EC2에 redis 설치
- [x] 모니터링 서버 구축
- [x] 에러 슬랙 연동

## 💬 기타 사항

-

**Comment by dahyen0o** [comment]
@sienna011022 WAF는 추후 도입하실 예정인가요?

**Comment by sienna011022** [comment]
이제 봤네요..WAF는 비용적 측면이 크기 떄문에, AWS 협약이된다면 고려해볼 예정입니다! 적극적이진 않아요
