### ISSUE TITLE
[feature] Users API

### ISSUE THREAD

**Issue by psyeon1120** [Floney-2023/Floney-Server#3]
## 📍 구현할 기능

> 카카오, 구글, 애플, 이메일 로그인 구현

## 🛠 작업 내용

- [x] 스프링 시큐리티 적용
- [ ] 카카오 로그인 API
- [ ] 구글 로그인 API
- [ ] 애플 로그인 API
- [x] 이메일 회원가입 API
- [x] 이메일 로그인 API
- [x] 로그아웃 API
- [x] 회원탈퇴 API
- [x] 프로필 이미지 변경 API
- [x] 닉네임 변경 API
- [x] 비밀번호 변경 API
- [x] 비밀번호 찾기 API
- [x] 인증메일 발송 API
- [ ] 마이페이지 조회 API

## 💬 기타 사항

- none

**Comment by dahyen0o** [comment]
못한거 따로 이슈로 생성함
