### ISSUE TITLE
[infra] 모니터링 서버 추가

### ISSUE THREAD

**Issue by dahyen0o** [Floney-2023/Floney-Server#321]
## 📍 구현할 기능

> 모니터링 서버 구축

## 🛠 작업 내용

- [ ] 모니터링 서버용 EC2 구축
- [ ] 프로메테우스 구축
- [ ] 그라파나 구축
- [ ] 로그 파일 연동 

## 💬 기타 사항

- 운영 서버에 모니터링 시스템을 구축하면, 운영 서버가 터진다면 모니터링도 불가능해지기 때문에, 따로 분리하는게 맞다고 생각합니다.
- 개발 서버 모니터링은 오버 스펙인것 같아요. 나중에 필요한 사항이 생기면, 넣는게 어떠신가요?

**Comment by dahyen0o** [comment]
@sienna011022 
> 운영 서버에 모니터링 시스템을 구축하면, 운영 서버가 터진다면 모니터링도 불가능해지기 때문에, 따로 분리하는게 맞다고 생각합니다.

네 좋습니다. 다만 서버비 때문에 운영팀에게 알려야하겠네요

> 개발 서버 모니터링은 오버 스펙인것 같아요. 나중에 필요한 사항이 생기면, 넣는게 어떠신가요?

별도 서버에 구축하는 게 오버 스펙인 건 동의하는데, 같은 서버 내에서는 구축하면 좋을 것 같습니다..! 추후 부하 테스트를 진행하거나, 어떤 이슈가 운영 서버에 올라가기 전 서버에 이상이 생길 지 보면 좋을 것 같아서요. 바쁘시면 얘는 천천히 해도 될 것 같습니다.

**Comment by sienna011022** [comment]
> 는데, 같은 서버 내에서는 구축하면 좋을 것 같습니다..! 추후 부하 테스트를 진행하거나, 어떤 이슈가 운영 서버에 올라가기 전 서버에 이상이 생길 지 보면 좋을 것 같아서요. 바쁘시면 얘는 천천히 해도 될 것 같습니다.

흠 그렇네요. 알겠습니다. 우선 실 운영서버 구축 먼저 진행하겠습니다.
