### ISSUE TITLE
[hotfix] 자산 upsert 쿼리에서 테이블을 소문자로 구분

### ISSUE THREAD

**Issue by dahyen0o** [Floney-2023/Floney-Server#335]
## 🐞 발생한 버그

참고 - https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html 

로컬 macOS의 설정값과 EC2 서버의 운영체제인 ubuntu의 설정값이 달라 
쿼리 내 테이블의 대문자를 소문자로 자동 변환하지 않아서 발생한 문제입니다.

**Comment by sienna011022** [comment]
확인했습니다
