### ISSUE TITLE
[feature] 이월 내역 리팩토링

### ISSUE THREAD

**Issue by sienna011022** [Floney-2023/Floney-Server#400]
## 📍 이슈 설명

이월 내역 동시성 처리

## 🛠 작업할 내용

✅ 구체적으로 작성해주세요

- [x] 잠재적으로 발생할 수 있는 이월 내역 동시성 처리를 진행한다.
- [x] 이월내역을 DB에서 한건씩 가져오는 조회 쿼리를 한번에 벌크 조회로 가져온다

**Comment by dahyen0o** [comment]
이월 설정을 저장하지 않도록 로직 수정
